import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { CartProvider } from "@/contexts/CartProvider";
import { NavBar } from "@/components/NavBar";
import { SideProvider } from "@/contexts/SideBarContext";
import {register} from 'swiper/element/bundle'
register()
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import { SearchProvider } from "@/contexts/SearchContext";

const montserrat = Montserrat({
  weight: ["300", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Jorri Pratas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={montserrat.className}>
      <body className="w-screen h-screen flex-col m-0 p-0 bg-white">
        <CartProvider>
          <SideProvider>
          <SearchProvider>
            <header>
              <NavBar hasIconAccount={true} hasIconCart={true} />
            </header>
            <div className="w-full h-full flex justify-center mt-10">
              <section className="w-full h-full flex mx-6 my-10">
                {children}
              </section>
            </div>
            </SearchProvider>
          </SideProvider>
        </CartProvider>
      </body>
    </html>
  );
}
