import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { CartProvider } from "@/contexts/CartProvider";

const montserrat = Montserrat({
  weight: ["300", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={montserrat.className}>
      <body className="w-screen h-screen flex-col m-0 p-0 ">
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
